[tool.black]
line-length = 100
target-version = ["py311"]
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true

[tool.ruff]
line-length = 110
target-version = "py311"
select = ["E", "F", "I", "B"]
ignore = ["E203"]  # match Black’s style
exclude = ["__pycache__", ".venv", "venv", "build", "dist"]

[tool.ruff.isort]
known-first-party = ["app", "pipelines", "common"]